### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by levrex** [AltschulerWu-Lab/MUSE#1]
Thanks for sharing this powerful tool!

I am wondering: are you guys considering to add functionality for more than 2 layers? I would like to apply this autoencoder strategy on 3+ data modalities.

**Comment by feng-bao-ucsf** [comment]
> Thanks for sharing this powerful tool!
> 
> I am wondering: are you guys considering to add functionality for more than 2 layers? I would like to apply this autoencoder strategy on 3+ data modalities.
Thanks for your interest. 
I think it is doable in both thoery and practice.  In our case, we focus on a specific biology question, so we did not test the model on data with more modalities.

**Comment by levrex** [comment]
Thanks for your response. I'll take a look.
