### ISSUE TITLE
Applying MUSE on human dorsolateral prefrontal cortex (http://research.libd.org/spatialLIBD dataset) 

### ISSUE THREAD

**Issue by KalinNonchev** [AltschulerWu-Lab/MUSE#3]
Hello,

thank you for making this model open-source. 
Currently, I am trying to apply MUSE on the human dorsolateral prefrontal cortex dataset from http://research.libd.org/spatialLIBD with known annotation (known clusters)

These are the steps I am following in pseudocode per sample
1. load spot matrix (n x genes) and normalize, transform and get the top 500 variable genes
2. load image and extract features with inception per spot ( n x 2048)
3. Applying PCA with n_components=100 on both matrix (only top 500 genes) and image features
4. run kmeans with k = 7 (running kmeans and not pheno because I want to specify the number of clusters apriori)
5. input data to muse_sc (with latent_dim=100, n_epochs=500, lambda_regul=5, lambda_super=5)
6. cluster with kmeans again the muse features

Could you confirm that my approach is correct? I am getting very low ARI and the clusters look random. Did you try MUSE on this dataset? Could you share your results as a reference?

**Comment by KalinNonchev** [comment]
PS: using both kmeans and pheno for clustering results in low performance

**Comment by KalinNonchev** [comment]
sample = 151673
<img width="470" alt="Screenshot 2023-03-27 at 12 55 49" src="https://user-images.githubusercontent.com/50597791/227908516-24f022eb-01ef-4922-9d0f-463553001126.png">

**Comment by fbao-fudan** [comment]
> sample = 151673 <img alt="Screenshot 2023-03-27 at 12 55 49" width="470" src="https://user-images.githubusercontent.com/50597791/227908516-24f022eb-01ef-4922-9d0f-463553001126.png">

Thank for your interest in our work. Yes we did test MUSE using this dataset. Here is your result and the joint analysis cannot capture the expected structure. When we debugged the result, we found the issue is in image modality. The clustering result from image provided completely different information compared with ground truth labels. I think two factors affecting it 1) a HE staining issue 2) brain tissue itself doesn't have rich morphological variations. Hope it helps. 
![image](https://user-images.githubusercontent.com/12905036/228014375-55bf1cf7-a4b6-417a-981d-720ee168f339.png)

**Comment by KalinNonchev** [comment]
Thank you for your input on this. Indeed, the image information looks different.
Could you also confirm the order of steps in the pseudocode and choice of the hyper parameters you were using?

**Comment by fbao-fudan** [comment]
Most steps look good. I only have several comments:
1. Variable gene numbers: you can choose a different number if you believe you can capture more information from that.
2. Typically I do not use PCA transformation on genes as we design a drop-out aware reconstruction loss for gene modality.  You can just input gene counts with log1p transform. 
3. You can use k-means in clustering. Ideally you can check if the clustering results can reflect the desired tissue structures. If the single modal clusters did not tell the expected information, usually it suggested the modality did not contain desired information, or even provided wrong information. Under this situation, we can expect the joint analysis cannot perform better. 
4. For hyperparameters, based on our calibration, the model usually performs quite stable with different values. 
Hope it helps!
