### ISSUE TITLE
why paper L is given by N = (n − 1) (n − 2) /2?it is not L is given by N = (n − 1) (n) /2

### ISSUE THREAD

**Issue by xhl-xhl** [AltschulerWu-Lab/MUSE#4]

**Comment by fbao-fudan** [comment]
I suppose you are asking questions on pairwise distance calculation. Here we exclude the diagonal elements in the distance matrix as they are all zeros.

**Comment by xhl-xhl** [comment]
![Snipaste_2023-05-04_21-40-11](https://user-images.githubusercontent.com/120104324/236222957-ce5ca762-906f-4f53-ada1-6c535fbdebbc.png)
Thanks,I know what you mean.However,for a n*n matrix, the number of elements(i < j) is  (n − 1) (n) /2.But size of L is given by N = (n − 1) (n − 2) /2 in paper.Maybe I was stupid,thanks!
