### ISSUE TITLE
Question about the segmentation step

### ISSUE THREAD

**Issue by statwangz** [AltschulerWu-Lab/MUSE#5]
Dear Feng,

Thank you for developing such great software.
If my understanding is correct, the files contained in `./image_feature_learning_tool/example_img/` are segmented patches, and each file (e.g., `Img_1.npy`) corresponds to one specific cell. Then I'm curious about how to segment the image and obtain segmented patches. Do you have any recommended methods?

Best regards,
Zhiwei

**Comment by fbao-fudan** [comment]
Hi Zhiwei,

Thanks for your interest in our work. We simply use the coordinates of spots as centers and  segment the region with a square window. It was done by calculation on HE image matrix; we did not use any segmentation tools. 

Hope it helps.
Feng

**Comment by statwangz** [comment]
> Hi Zhiwei,
> 
> Thanks for your interest in our work. We simply use the coordinates of spots as centers and segment the region with a square window. It was done by calculation on HE image matrix; we did not use any segmentation tools.
> 
> Hope it helps. Feng

Dear Feng,

Thank you for the reply!

Best,
Zhiwei
