### ISSUE TITLE
Questions on Processing STARMap and Seqfish+ datasets

### ISSUE THREAD

**Issue by fym0503** [AltschulerWu-Lab/MUSE#6]
Dear authors,
       In your paper, you use several real world datasets including STARMap and Seqfish+ datasets. Could you please provide some processing scripts for these datasets? The orginal data for STARMap is even missing (https://www.starmapresources.com/) and their repos lack proper instructions. Thanks a lot if you could help !

**Comment by fbao-fudan** [comment]
Thanks for your interest in our work. For data processing, we used the standard transcript data processing pipeline from scanpy or seurat. For image processing, we have a tool here https://github.com/AltschulerWu-Lab/MUSE/tree/master/image_feature_learning_tool. We also noticed the authors in STARmap stopped the support for the dataset website. Please reach out to them for detailed information.
