### ISSUE TITLE
Question regarding train/test split.

### ISSUE THREAD

**Issue by boqchen** [AltschulerWu-Lab/MUSE#7]
Hi Feng,

Thanks for the great work!

For the demo code it seems that you trained and tested on the same data (1k cells were generated --> train to get muse features on these 1k cells --> performed clustering using learned muse features on these 1k cells). This is quite different to common machine learning framework where data is typically divided into train and test sets, i.e., testing data should not be used in the training stage. Can you elaborate more on this?

Thanks in advance!

**Comment by fbao-fudan** [comment]
Thanks for your interest in our work. 

Because the whole model is an unsupervised learning framework, we will not apply learned parameters to other datasets for generalization. Our goal is to learn good representations just for the tissue we study. An example is PCA, it is less meaningful that you train on subset and apply the model to all.  Hope it helps.

**Comment by boqchen** [comment]
Hi Feng,

Thanks for your prompt reply!

If I understand correctly, the "dataset" you consider is essentially one tissue biopsy (i.e., one tissue whole-slide). And within this tissue slide, each spot you generate ST for is considered as one "data point". Thus, e.g., although the "PDAC dataset" you benchmarked MUSE on consists of several slides (PDAC-A ST1, PDAC-B ST1, etc.), they are considered as different "datasets" as they are obtained from different tissue biopsies.

**Comment by fbao-fudan** [comment]
> Hi Feng,
> 
> Thanks for your prompt reply!
> 
> If I understand correctly, the "dataset" you consider is essentially one tissue biopsy (i.e., one tissue whole-slide). And within this tissue slide, each spot you generate ST for is considered as one "data point". Thus, e.g., although the "PDAC dataset" you benchmarked MUSE on consists of several slides (PDAC-A ST1, PDAC-B ST1, etc.), they are considered as different "datasets" as they are obtained from different tissue biopsies.

Yes that is correct. We did not combine multi datasets, even they are from the same study.
